services:
  # --- SERVIÇO DO BACKEND (API) ---
  api:
    build:
      context: ./backend-lolli-pet
      dockerfile: Dockerfile
    ports:
      # Mapeando a porta INTERNA 3001 para a EXTERNA 3001
      - "3001:3001"
    volumes:
      - ./backend-lolli-pet:/app
      - /app/node_modules
    env_file:
      - ./.env # Lendo variáveis do .env na raiz
    depends_on:
      - db

  # --- SERVIÇO DO FRONTEND (WEB) ---
  web:
    build:
      context: ./lolli-pet-web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./lolli-pet-web:/app
      - /app/node_modules
    environment:
      # Ajustando para o nome do serviço interno 'api'
      - VITE_API_URL=http://api:3001

  # --- SERVIÇO DE BANCO DE DADOS (MySQL) ---
  db:
    image: mysql:8.0
    container_name: lolli-pet-db
    restart: always
    ports:
      # Mapeia a porta INTERNA 3306 (padrão MySQL) para a porta EXTERNA 3307
      - "3309:3306"
    environment:
      # Variáveis essenciais para o MySQL
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USERNAME}
    volumes:
      # CORREÇÃO CRÍTICA: Monta o volume 'db_data' no caminho correto do MySQL
      - db_data:/var/lib/mysql

# --- DECLARAÇÃO DE VOLUMES ---
volumes:
  db_data: # Declara o volume usado pelo serviço 'db'